
project_id = "dqymhupheqkwasfrkcqs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
enabled = true
port = 54322

[edge_functions]
enabled = true

[functions.analyze-strain]
verify_jwt = false

[functions.cannabis-chat]
verify_jwt = false
