
import { useEffect, useState } from 'react';
import { Search, Database, Zap } from 'lucide-react';
import { Progress } from '@/components/ui/progress';

interface GenerationProgressProps {
  isGenerating: boolean;
  generationStep: number;
  progress: number;
  currentStepText: string;
  generationSteps: string[];
}

const GenerationProgress = ({
  isGenerating,
  generationStep,
  progress,
  currentStepText,
  generationSteps
}: GenerationProgressProps) => {
  if (!isGenerating) return null;

  const getStepIcon = () => {
    if (generationStep < 2) return <Search className="h-4 w-4 text-green-600 animate-pulse" />;
    if (generationStep < 4) return <Database className="h-4 w-4 text-blue-600 animate-pulse" />;
    return <Zap className="h-4 w-4 text-purple-600 animate-pulse" />;
  };

  return (
    <div className="space-y-3 animate-fade-in">
      <div className="bg-gradient-to-r from-green-900/20 to-blue-900/20 border border-green-400/30 rounded-lg p-4 backdrop-blur-sm">
        <div className="flex items-center gap-3 mb-3">
          <div className="flex items-center gap-2">
            {getStepIcon()}
            <span className="text-sm font-medium text-green-300 font-mono">
              CANNABIS DATABASE SEARCH
            </span>
          </div>
          <div className="text-xs text-green-400 bg-green-900/30 px-2 py-1 rounded-full border border-green-400/50">
            {Math.round(progress)}%
          </div>
        </div>
        
        <Progress value={progress} className="mb-3 h-2 bg-gray-800" />
        
        <div className="text-sm text-green-300 min-h-[20px] font-mono tracking-wide">
          {currentStepText}
          <span className="animate-pulse text-green-400">_</span>
        </div>
        
        <div className="mt-2 text-xs text-green-400/70 font-mono">
          Searching premium cannabis databases...
        </div>
      </div>
      
      {/* AI Disclaimer */}
      <div className="text-xs text-gray-400 text-center bg-gray-900/50 rounded p-2 border border-gray-600/30">
        ⚠️ All information generated by AI • For recreation and enjoyment only • Not for medical purposes
      </div>
    </div>
  );
};

export default GenerationProgress;
