
import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useRealtimeStrainStore } from '@/stores/useRealtimeStrainStore';
import { useAuth } from '@/contexts/AuthContext';
import { Strain } from '@/types/strain';
import StrainDashboard from '@/components/StrainDashboard';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Cannabis, Lock, Database } from 'lucide-react';

const StrainPage = () => {
  const { strainName } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { strains, isLoading } = useRealtimeStrainStore();
  const [strain, setStrain] = useState<Strain | null>(null);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (isLoading || !strainName) return;

    // Find strain by name (case-insensitive, handle URL-friendly names)
    const decodedName = decodeURIComponent(strainName).replace(/-/g, ' ');
    const foundStrain = strains.find(s => 
      s.name.toLowerCase() === decodedName.toLowerCase() ||
      s.name.toLowerCase().replace(/\s+/g, '-') === strainName.toLowerCase()
    );

    if (foundStrain) {
      setStrain(foundStrain);
      setNotFound(false);
    } else {
      setStrain(null);
      setNotFound(true);
    }
  }, [strains, strainName, isLoading]);

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (notFound) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <Card className="w-full max-w-md bg-card border-border">
          <CardHeader className="text-center">
            <div className="flex items-center justify-center mb-4">
              <Database className="h-8 w-8 text-orange-500 mr-2" />
              <Cannabis className="h-8 w-8 text-primary" />
            </div>
            <CardTitle className="text-2xl text-foreground">
              Strain Not Found
            </CardTitle>
            <CardDescription>
              "{decodeURIComponent(strainName || '').replace(/-/g, ' ')}" isn't in our database yet.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 text-center">
            {user ? (
              <div className="space-y-4">
                <p className="text-sm text-muted-foreground">
                  As an authenticated user, you can add this strain to our shared database.
                </p>
                <Button 
                  onClick={() => navigate('/')}
                  className="w-full"
                >
                  Add to Database
                </Button>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="flex items-center justify-center p-4 bg-orange-500/10 border border-orange-500/20 rounded-lg">
                  <Lock className="h-5 w-5 text-orange-500 mr-2" />
                  <p className="text-sm text-orange-400">
                    Sign in required to add strains to the database
                  </p>
                </div>
                <div className="space-y-2">
                  <Button 
                    onClick={() => navigate('/auth')}
                    className="w-full"
                  >
                    Sign In to Add Strain
                  </Button>
                  <Button 
                    variant="outline"
                    onClick={() => navigate('/')}
                    className="w-full"
                  >
                    Browse Database
                  </Button>
                </div>
              </div>
            )}
            
            <div className="mt-6 pt-4 border-t border-border">
              <p className="text-xs text-muted-foreground text-center">
                ⚠️ All information generated by AI • For recreation and enjoyment only • Not for medical purposes
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!strain) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <p className="text-muted-foreground">Loading strain information...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto py-8">
        <Button 
          variant="ghost" 
          onClick={() => navigate(-1)}
          className="mb-6"
        >
          ← Back
        </Button>
        
        <StrainDashboard strain={strain} />
        
        {/* AI Disclaimer */}
        <div className="mt-8 p-4 bg-muted/50 rounded-lg border border-border">
          <p className="text-xs text-muted-foreground text-center">
            ⚠️ All information generated by AI • For recreation and enjoyment only • Not for medical purposes
          </p>
        </div>
      </div>
    </div>
  );
};

export default StrainPage;
