// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqymhupheqkwasfrkcqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxeW1odXBoZXFrd2FzZnJrY3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODQ0NzQsImV4cCI6MjA2NTM2MDQ3NH0.V47liXKGJg4a9rtA8q-I-SfQB1UlnDaBf8UKEuqj4C8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);